### PR TITLE
Support the updateZoneRecord method

### PR DESCRIPTION
**Pull request by jacobsvante**
Uses the ZoneRecord object's configured information when sending the request. So it's used like this:

``` python
>>> zr1 = subdomain.get_zonerecords()[0]
>>> zr1.rdata = '123.123.123.123'
>>> zr1.update()
True
```

### CODE REVIEW

**Comment by anderspetersson** [comment]
Thanks!

**Comment by jacobsvante** [comment]
NP! Perhaps we could see a new release on PyPI? :wink:

**Comment by anderspetersson** [comment]
Yep, will do tonight if I get time.
Den 9 sep 2015 13:44 skrev "Jacob Magnusson" notifications@github.com:

**Comment by jacobsvante** [comment]
Awesome!

**Comment by anderspetersson** [comment]
Hello!

New message, please read http://gresanoia.com/against.php?c4

Anders Petersson

**Comment by anderspetersson** [comment]
Hi,

I have recently tried this stuff and it helped me, that's no joke! Read more here http://thuntydefe.airforcecomics.com/aesyyh

Thx, Anders Petersson

**Comment by anderspetersson** [comment]
Dear friend! 

I've started a new project recently, so you can find some  examples of my  recenr works  here http://tendency.broadspectrumit.com/aeglj

Warmest regards, Anders Petersson

**Pull request merged**
